ProductPlatform/Controllers/TablesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using ProductPlatform.Models;

namespace ProductPlatform.Controllers
{
    public class TablesController : Controller
    {
        private readonly ProductPlatformContext _context;
        private readonly IMapper _mapper;

        public TablesController(ProductPlatformContext context)
        {
            _context = context;
            var config = new MapperConfiguration(cfg =>
            {
                var contractors = _context.Contractors.ToList();
                var customers = _context.Customers.ToList();
                var projects = _context.Projects.ToList();
                cfg.CreateMap<Customer, CustomerViewModel>();
                cfg.CreateMap<Contractor, ContractorViewModel>();
                cfg.CreateMap<Project, ProjectViewModel>()
                    .ForMember("Contractor", prop => prop.MapFrom(project => contractors.Single(c => c.ContractorID == project.ContractorID).FullName));
                cfg.CreateMap<CodeRequest, CodeRequestViewModel>()
                    .ForMember("Customer", prop => prop.MapFrom(cr => customers.Single(c => c.CustomerID == cr.CustomerID).FullName))
                    .ForMember("Project", prop => prop.MapFrom(cr => projects.Single(p => p.ProjectID == cr.ProjectID).Name));
            });
            _mapper = new Mapper(config);
        }

        [HttpGet]
        [Route("tables")]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("tables/customers")]
        public ActionResult Customers()
        {
            var data = _mapper.Map<IEnumerable<Customer>, List<CustomerViewModel>>(_context.Customers);
            return View(data);
        }

        [HttpGet]
        [Route("tables/contractors")]
        public ActionResult Contractors()
        {
            var data = _mapper.Map<IEnumerable<Contractor>, List<ContractorViewModel>>(_context.Contractors);
            return View(data);
        }

        [HttpGet]
        [Route("tables/projects")]
        public ActionResult Projects()
        {
            var data = _mapper.Map<IEnumerable<Project>, List<ProjectViewModel>>(_context.Projects);
            return View(data);
        }

        [HttpGet]
        [Route("tables/coderequests")]
        public ActionResult CodeRequests()
        {
            var data = _mapper.Map<IEnumerable<CodeRequest>, List<CodeRequestViewModel>>(_context.CodeRequests);
            return View(data);
        }
    }
}

ProductPlatform/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductPlatform</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ProductPlatform</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" href='@Url.Action("Customers", "Tables")'>Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" href='@Url.Action("Contractors", "Tables")'>Contractors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" href='@Url.Action("Projects", "Tables")'>Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" href='@Url.Action("CodeRequests", "Tables")'>Code requests</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ProductPlatform - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>